# This workflow will build a golang project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-go

name: Go

on:
  push:
    branches: [ "main", "fix-build" ]
  pull_request:
    branches: [ "main" ]


jobs:
  build:
    name: Build and test on ${{ matrix.os }} ${{ matrix.arch }}
    strategy:
      matrix:
        os: [darwin, linux]
        arch: [amd64, arm64]
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Set up Go
      uses: actions/setup-go@v5
      with:
        go-version: '1.23.2'
        cache-dependency-path: |
               browser/go.sum
               code-gen/go.sum

    - name: Build
      working-directory: ./browser
      run: |
        go get
        go build -v ./...
        go test -v ./...
